Su 245
fiterlatam/fineract-template pull request #859
Opened 2024-06-28 19:12 UTC by faheem205

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-06-28 21:54 UTC, faheem205 commented
[(https://fiterio.atlassian.net/browse/SU-245)]

This ticket fixes installment interest calculation based on formula provided by the client, Mandatory Insurance Charge calculation  and VAT Term Charge Calculation cases (Percentage Based which is provided at the time of adding the charge, Percentage of Outstanding Balance Based and table based where charge percentage is present in a table against number of repayments)

2024-07-01 12:49 UTC, fiter-julius-oketayot requested changes

2024-07-01 12:49 UTC, fiter-julius-oketayot commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/loanschedule/domain/LoanApplicationTerms.java
>          Money totalPmtForThisInstallment = calculateTotalDueForEqualInstallmentRepaymentPeriod(periodicInterestRateForRepaymentPeriod,
@faheem205 the idea of using the method periodicInterestRateWithOriginalRate() was to maintain a constant EMI for a loan even after a rescheduling

2024-07-01 12:59 UTC, fiter-julius-oketayot requested changes

2024-07-01 12:59 UTC, fiter-julius-oketayot commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/loanschedule/domain/LoanApplicationTerms.java
> -        }
This is using interestRatePerPeriod instead of annualNominalInterest which be changed

2024-07-02 10:49 UTC, fiter-julius-oketayot approved these changes

2024-07-02 11:26 UTC, merged